### ISSUE TITLE
Purge Operation: Response status code for invalid regex 

### ISSUE THREAD

**Issue by devbbc** [davidjwbbc/rt-5gms-application-server#2]
If the purge regex pattern is invalid, the Application Server raises an exception and produces a local error log. However, the Application Server returns a response with status code 200 to the Application Function.

I think the response should have status code 500 when the regular expression for Purge operation is invalid.

**Comment by davidjwbbc** [comment]
If the regex is wrong then that is a problem with the client request, so the response should be a 4xx.

**Comment by devbbc** [comment]
We reviewed in today's team meeting and decided to go with 422 (unprocessable entity).

I will raise this issue against the development branch of the main 5G-MAG repo.

**Comment by devbbc** [comment]
Raised bug as  #52.
